# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

FROM golang:1.26.5

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 \
    tcpdump \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/onsi/ginkgo/v2/ginkgo@v2.32.0

WORKDIR /src
